---
apiVersion: v1
kind: Service
metadata:
  name: shopping
  labels:
    app: shopping
    service: shopping
spec:
  ports:
    - name: http-shopping
      protocol: TCP
      port: 3000
  selector:
    app: shopping
    service: shopping
---
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: shopping
  labels:
    app: shopping
    service: shopping
spec:
  selector:
    matchLabels:
      app: shopping
      service: shopping
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: shopping
        service: shopping
    spec:
      containers:
      - image: harbor.tanzuworld.com/niran-acme/shopping-azure-west:v0.2
        name: shopping
        env:
        - name: FRONTEND_PORT
          value: '3000'
        - name: USERS_HOST
          value: 'users.acme.local'
        - name: CATALOG_HOST
          value: 'catalog.acme.local'
        - name: ORDER_HOST
          value: 'order.acme.local'
        - name: CART_HOST
          value: 'cart.acme.local'
        - name: USERS_PORT
          value: '8081'
        - name: CATALOG_PORT
          value: '8082'
        - name: CART_PORT
          value: '5000'
        - name: ORDER_PORT
          value: '6000'
        ports:
        - containerPort: 3000
          name: http-shopping
---
